# Base configs
baseurl: "https://aterribili.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-133561997-1"

# UI configs
title: "Photography by Abner Terribili"
subtitle: ""
author: "Abner Terribili"
header:
 title: "Photography"
 subtitle: "by Abner Terribili"
footer:
 name: "Abner Terribili"
 bio: "Developer at Digaxis and Nubank, cyclist and bird photographer"
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/aterribili"
  github: "https://www.github.com/aterribili"
  email: "abner.terribili@gmail.com"
